
# COOL BANNER

source = ~/.config/hypr/components/aliases.conf
source = ~/.config/hypr/components/monitors.conf
source = ~/.config/hypr/components/autostart.conf
source = ~/.config/hypr/components/environment.conf
source = ~/.config/hypr/components/permissions.conf
source = ~/.config/hypr/components/colors.conf
source = ~/.config/hypr/components/look_and_feel.conf
source = ~/.config/hypr/components/input.conf
source = ~/.config/hypr/components/keybinds.conf
source = ~/.config/hypr/components/windows_and_workspaces.conf
