#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hypr.land/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = XCURSOR_THEME,Volantes Cursors
# env = HYPRCURSOR_SIZE,24

# for nvidia
# env = LIBVA_DRIVER_NAME,nvidia
# env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# for prime (without this it doesn't work, doesn't read stuff set with nixos)
# env = WLR_DRM_DEVICES,/dev/dri/card1
# env =  AQ_DRM_DEVICES,/dev/dri/card1

# idk if this gives anything
# env = __GLX_VENDOR_LIBRARY_NAME,mesa
# env = WLR_DRM_DEVICES,/dev/dri/by-path/pci-0000:06:00.0-card
# env = LIBVA_DRIVER_NAME,radeonsi
# env = VDPAU_DRIVER,va_gl

# for prime + whatever, should prioritize igpu, 
# fallback to dgpu + mulihead support
# needs udev rules seen on https://wiki.hypr.land/Configuring/Multi-GPU/#creating-consistent-device-paths-for-specific-cards
env =  AQ_DRM_DEVICES,/dev/dri/amd-igpu:/dev/dri/nvidia-dgpu
