################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/

source = ~/.config/hypr/components/aliases.conf

monitor = $mon1, 1920x1080, 0x0, 1
monitor = $mon2, 1920x1080, 1920x700, 1
