##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
windowrule = noblur, class:^(kitty)$|^(floating-kitty)$,title:.* - Nvim
windowrule = float, class:^(floating-kitty)$

# games
$games = class:steam_app_.*|^(cs2)$|^(Celeste.bin.x86_64)$|^(Celeste)$|^(Streaming Client)$|^(Minecraft.*)$|^(valheim.x86_64)$
windowrule = immediate,  $games
windowrule = fullscreen, $games
windowrulev2 = workspace 2, $games

# browser
$browser = class:^(vivaldi-stable)$|^(zen)$
windowrulev2 = workspace 1, $browser
windowrule = bordersize 0, $browser

$videopip = title:^(Picture in picture)$
windowrulev2 = float, $videopip
windowrulev2 = pin, $videopip
windowrulev2 = size 480 270, $videopip
windowrulev2 = move 1440 810, $videopip

# messagers
$messager = class:^(vesktop)$|^(org.telegram.desktop)$
windowrulev2 = workspace 3, $messager

# discord popout
windowrulev2 = float, initialTitle:^Discord Popout$
windowrulev2 = pin, initialTitle:^Discord Popout$
windowrulev2 = size 480 270, initialTitle:^Discord Popout$
windowrulev2 = move 1440 810, initialTitle:^Discord Popout$

# music apps
$music = class:^(spotify)$
windowrulev2 = float, class:^(ncmpcpp-custom)$
windowrulev2 = size 960 540, class:^(ncmpcpp-custom)$
windowrulev2 = workspace 4, $music

# game launchers
$gaming = class:^(steam)$|^(com.usebottles.bottles)$
windowrulev2 = workspace 5, $gaming

# other stuff
windowrulev2 = float, class:^(org.gnome.Calculator)$



# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0


# bind workspaces to monitors
workspace = 1,  monitor:$mon1, persistent:true
workspace = 2,  monitor:$mon1, persistent:true
workspace = 3,  monitor:$mon1, persistent:true
workspace = 4,  monitor:$mon1, persistent:true
workspace = 5,  monitor:$mon1, persistent:true

workspace = 6,  monitor:$mon2
workspace = 7,  monitor:$mon2
workspace = 8,  monitor:$mon2
workspace = 9,  monitor:$mon2
workspace = 10, monitor:$mon2
