{ pkgs, config, ... }:

{
  imports = [
    # TODO: idk how modules work yet

    # basically essential
    ./modules/ui.nix
    ./modules/fonts.nix
    ./modules/hardware.nix
    ./modules/software.nix
    ./modules/services.nix
    ./modules/users.nix

    # personal/optional
    ./modules/gaming.nix
    ./modules/prime.nix
    ./modules/spicetify-comfy.nix
    # ./modules/legion.nix
    ./modules/faster-boot.nix

    # TODO: this should probably be autogenerated and is suboptimal
    ./hardware-configuration.nix
  ];

  # enable spyware
  nixpkgs.config.allowUnfree = true;
  # very dangerous bleeding edge stuff here
  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  networking.hostName = "nixos"; # Define your hostname.
  networking.networkmanager.enable = true;

  time.timeZone = "Europe/Warsaw";
  i18n.defaultLocale = "en_US.UTF-8";
  i18n.extraLocaleSettings = {
    LC_ADDRESS = "pl_PL.UTF-8";
    LC_IDENTIFICATION = "pl_PL.UTF-8";
    LC_MEASUREMENT = "pl_PL.UTF-8";
    LC_MONETARY = "pl_PL.UTF-8";
    LC_NAME = "pl_PL.UTF-8";
    LC_NUMERIC = "pl_PL.UTF-8";
    LC_PAPER = "pl_PL.UTF-8";
    LC_TELEPHONE = "pl_PL.UTF-8";
    LC_TIME = "pl_PL.UTF-8";
  };

  services.xserver.xkb = {
    layout = "us";
    variant = "";
  };

  boot = {
    # plymouth = {
    #   enable = true;
    #   theme = "circle_hud";
    #   themePackages = with pkgs; [
    #     # By default we would install all themes
    #     (adi1090x-plymouth-themes.override {
    #       selected_themes = [ "circle_hud" ];
    #     })
    #   ];
    # };

    # something related to boot logs (probably)
    consoleLogLevel = 3;
    initrd.verbose = false;
    kernelParams = [
      "quiet"
      "splash"
      "boot.shell_on_fail"
      "loglevel=3"
      "rd.udev.log_level=3"
      "udev.log_priority=3"
      "rd.systemd.show_status=false"
    ];

    # i have ONE ntfs partition and it needs to go
    supportedFilesystems = ["ntfs"];

    # time to choose derivation
    # (0 still lets you press ESC)
    loader.timeout = 0;

    loader.systemd-boot.enable = true;
    loader.efi.canTouchEfiVariables = true;
    kernelPackages = pkgs.linuxPackages_latest;
  };

  system.stateVersion = "25.05"; # DONT CHANGE
}
